### PR TITLE
Python3 version

### PR DESCRIPTION
**Pull request by iherman**
Finalized a Python 3 version

### CODE REVIEW

**Review by nicholascar — CHANGES_REQUESTED** [review]
In the changes to file `Doc-pyRdfa/pyRdfa.host-module.html`, `pyRdfa/__init__.py ` & `pyRdfa/host/__init__.py`, you've stated that dependencies are:

```
<a href="http://rdflib.net" target="_top">RDFLib package</a> version 5 or higher
```

and

```
Python version 2.7 or 3.8 or higher
```

These are both incorrect: For the first point, I'm not sure this module now works with RDFlib 5.0.0 and for the second, RDFlib 5.0.0 works with Python 2.7 & 3.4+. 

Otherwise changes seem fine, if somewhat out-of-date since these changes were mad in January? i.e. before RDFlib 5.0.0.

Any reason to note 3.8+ as you've done? Of course you *can* have whatever restrictions you like in this plugin but best would to be in sync with RDFlib core.

RDFlib 6.0.0 will be Python 3.6+.

**Comment by iherman** [comment]
@nicholascar thanks. I realized that, actually, there was a discrepancy in the documentation, so I had to regenerate it...

That being said:

>  I'm not sure this module now works with RDFlib 5.0.0 and for the second, RDFlib 5.0.0 works with Python 2.7 & 3.4+.

I am not sure how the dates got tangled, but the changes were actually made in April. I do not remember exactly when 5.0.0 came out, but that is certainly the version I run on my machine and I tested with. I did not test this with earlier versions of RDFLib, hence that dependency. 

As for the 3.4 vs. 3.8: I must admit I do not remember the details. What I do know (because I was pretty upset about it) is that there was some specific, and backward-incompatible change between 3.8 and a previous version, which created some problems with my code. I know I had to fight with this sometimes at the beginning of the year; however, subsequent private events (some health issues, COVID lockdown in France, etc...) wiped out my memory.  But I do know that I needed to upgrade my local Python3 version to get things running. So yes, I am afraid Python3.8 is necessary for this module:-(

(Sorry to be a bit vague...)

**Comment by FlorianLudwig** [comment]
@iherman @nicholascar I tried the lib with python3.5 and python3.6 by running `scripts/localRDFa.py` on a small html file and had no issues.

With even python 3.5 having reached end of life, I would not spend any time on python 3.4.

**Comment by nicholascar** [comment]
I’ll merge this shortly and review state of the module in general. 

We are preparing to incorporate JSON-LD and a few other bits and pieces into RDFlib core, so if dependencies can be aligned, this can go in too and thus both increase RDFLib capabilities and reduce maintenance burden.  We will have to test this integration all properly of course, but that’s do-able.

**Comment by iherman** [comment]
B.t.w., @nicholascar, I think I have taken care of your issues above, maybe you want to update your review...

**Pull request merged**
